# Usage: cmake -P copy_dlls.cmake -DSRC_DIR=<source> -DDEST_DIR=<destination>
# -DOPTIONAL=<bool>

if(NOT DEFINED SRC_DIR)
    message(FATAL_ERROR "SRC_DIR is not defined")
endif()
if(NOT DEFINED DEST_DIR)
    message(FATAL_ERROR "DEST_DIR is not defined")
endif()
if(NOT EXISTS "${SRC_DIR}")
    if(NOT DEFINED OPTIONAL OR OPTIONAL)
        return()
    else()
        message(FATAL_ERROR "Directory does not exist: ${SRC_DIR}")
    endif()
endif()
file(MAKE_DIRECTORY "${DEST_DIR}")
file(GLOB DLL_FILES "${SRC_DIR}/*.dll")
if(NOT DLL_FILES)
    return()
endif()
foreach(DLL_FILE IN LISTS DLL_FILES)
    get_filename_component(DLL_FILE_NAME "${DLL_FILE}" NAME)
    set(DEST_FILE "${DEST_DIR}/${DLL_FILE_NAME}")
    if("${DLL_FILE}" STREQUAL "${DEST_FILE}")
        message(WARNING "Source ${DLL_FILE} equals destination ${DEST_FILE}")
        continue()
    endif()
    if(EXISTS "${DEST_FILE}")
        file(SHA256 "${DLL_FILE}" DLL_FILE_HASH)
        file(SHA256 "${DEST_FILE}" DEST_FILE_HASH)
    else()
        set(DLL_FILE_HASH "")
        set(DEST_FILE_HASH "differs")
    endif()
    if(NOT DLL_FILE_HASH STREQUAL DEST_FILE_HASH)
        if(NOT DEFINED QUIET OR NOT QUIET)
            message("Copied ${DLL_FILE}")
        endif()
        file(COPY "${DLL_FILE}" DESTINATION "${DEST_DIR}")
    else()
        if(NOT DEFINED QUIET OR NOT QUIET)
            message("Copied ${DLL_FILE} (up-to-date)")
        endif()
    endif()
endforeach()
