protocol:
  base_url: http://localhost:8080
  chunk_buffer_size: 8
  constraints:
    chunk_size: 65536 # 64 KiB
    max_content_size: 67108864 # 64 MiB
    accepted_content_types:
      - text/html
      - image/png
      - image/jpeg
    cache_duration: 30s
  intervals:
    write_wait: 10s
    pong_wait: 60s
    ping_interval: 48s
    timeout_duration: 30s
    timeout_interval: 8s
http:
  write_timeout: 4s
  read_timeout: 10s
  idle_timeout: 30s
log:
  level: INFO
